##
#This class is generated by gem ActiveAdmin for creating Admin users
# the class has no additional code
ActiveAdmin.register AdminUser do
  ##
  # the index page of admin_users

  index do                            
    column :email                     
    column :current_sign_in_at        
    column :last_sign_in_at           
    column :sign_in_count             
    default_actions                   
  end                                 

  filter :email                       

  form do |f|                         
    f.inputs "Admin Details" do       
      f.input :email                  
      f.input :password               
      f.input :password_confirmation  
    end                               
    f.actions                         
  end
end                                   
