##
#This class is generated by gem ActiveAdmin for creating Admin users
# the class has the following changes:
# 1- changed the default test
# 2- added recent orders
# 3- added recent products
ActiveAdmin.register_page "Dashboard" do

  menu :priority => 1, :label => proc{ I18n.t("active_admin.dashboard") }

  content :title => proc{ I18n.t("active_admin.dashboard") } do
    div :class => "blank_slate_container", :id => "dashboard_default_message" do
      span :class => "blank_slate" do
        ##
        # this is the message that is shown in the center of the page
        h3 'welcome to the Administration index page'
        small 'here you can see the recent Orders and products'
      end
    end



    columns do
      ##
      # column for recent Orders
       column do
         panel "Recent Orders" do
           ul do
             Order.last(5).map do |order|
               li link_to(order.name, admin_order_path(order))
             end
           end
         end
       end

       column do
         ##
         # column for recent Products
         panel "Recent Products" do
           ul do
             Product.last(5).map do |prod|
               li link_to(prod.name, admin_product_path(prod))
             end
           end
         end
       end
    end
  end # content
end
