##
#This class is generated by gem ActiveAdmin for creating Admin users
# the class has the following changes:
# 1- adding <tt> render 'admin/order'</tt>
ActiveAdmin.register Order do
  show do
    render 'admin/order'
  end
end
