##
#* Cart database model
#* generated by scaffold
class Cart < ActiveRecord::Base
  # attr_accessible :title, :body
  ## the following relations are described in project.rdoc
  has_many :line_items , :dependent => :destroy

  def add_product(product_id)
    ##
    # the product is reformed into a line_item with quantity and added to the cart
    current_item = line_items.where(:product_id => product_id).first
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(:product_id => product_id)
    end
    current_item
  end

  def total_price
    ##
    # the method is used in the cart in index page
    line_items.to_a.sum { |item| item.total_price }
  end

end
