##
#* Line_Item database model
#* generated by scaffold
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id ,:product ,:cart ,:quantity
  ##* the following relations are described in project.rdoc
  belongs_to :cart
  belongs_to :product
  belongs_to :order
  def total_price
    ##
    # returns the price of each line_item
    product.price * quantity
  end


end
