##
#* Order database model
#* generated by scaffold
class Order < ActiveRecord::Base
  attr_accessible :address, :email, :name, :pay_type
  ##
  # the following relations are described in project.rdoc
  has_many :line_items , :dependent => :destroy
  ##
  # the two common payment types
  PAYMENT_TYPES = [ "Direct pay after delivery" , "Credit card"  ]
  ##
  #* validators check the form to have the correct values
  #* any problems with the form is shown to him , after he tries to place the order
  validates :name, :address, :email, :pay_type, :presence => true
  validates :pay_type, :inclusion => PAYMENT_TYPES

  def add_line_items_from_cart(cart)
    ##
    # the line_items are moved into the order
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

end
